### ISSUE TITLE
Was hast du hier gemach

### ISSUE THREAD

**Issue by felix2uni** [felix2uni/praktikum#3]
@dennis-phy
https://github.com/felix2uni/praktikum/blob/82f3ab60ddfdb0aded41fb9577cb21486b2f823b/V351/content/auswertung.tex#L149-L151

Wozu gehören diese Zeilen?
Die haben einen Fehler beim Kompilieren verursacht.

**Comment by dennis-phy** [comment]
Die sind ein Überbleibsel, das ich nicht korrekt rausgelöscht habe, sorry. Spielt auch keine Rolle, ich lade eh gleich die neue Version von der Auswertung hoch.

**Comment by felix2uni** [comment]
Hast du schon?
